export interface NavItem {
  name: string
  url: string
  desc: string
  icon?: string
}

export interface NavCategory {
  title: string
  icon: string
  color: string
  items: NavItem[]
}

export const navCategories: NavCategory[] = [
  {
    title: '搜索引擎',
    icon: '🔍',
    color: 'from-blue-500 to-cyan-500',
    items: [
      { name: 'Google', url: 'https://www.google.com', desc: '全球最大搜索引擎' },
      { name: 'Bing', url: 'https://www.bing.com', desc: '微软搜索引擎，集成 Copilot' },
      { name: 'DuckDuckGo', url: 'https://duckduckgo.com', desc: '隐私优先，无追踪' },
      { name: 'Brave Search', url: 'https://search.brave.com', desc: '独立索引，无追踪' },
      { name: 'Perplexity', url: 'https://www.perplexity.ai', desc: 'AI 搜索，带引用来源' },
      { name: 'Yandex', url: 'https://yandex.com', desc: '俄罗斯最大搜索引擎' },
      { name: 'Startpage', url: 'https://www.startpage.com', desc: 'Google 结果 + 隐私保护' },
      { name: 'Wiby', url: 'https://wiby.me', desc: '复古网页搜索引擎' },
      { name: 'SearXNG', url: 'https://searx.space', desc: '开源聚合搜索引擎' },
      { name: 'Magi', url: 'https://magi.com', desc: 'AI 知识搜索引擎' },
      { name: 'Yep', url: 'https://yep.com', desc: 'Ahrefs 出品，90/10 利润分成' },
      { name: 'Ecosia', url: 'https://www.ecosia.org', desc: '搜索收入种树，环保引擎' },
    ],
  },
  {
    title: 'AI 导航',
    icon: '🤖',
    color: 'from-indigo-500 to-violet-500',
    items: [
      { name: 'ChatGPT', url: 'https://chat.openai.com', desc: 'OpenAI 对话模型' },
      { name: 'Claude', url: 'https://claude.ai', desc: 'Anthropic AI，长文本强' },
      { name: 'Gemini', url: 'https://gemini.google.com', desc: 'Google 多模态 AI' },
      { name: 'DeepSeek', url: 'https://chat.deepseek.com', desc: '国产开源大模型' },
      { name: 'Midjourney', url: 'https://www.midjourney.com', desc: 'AI 图像生成标杆' },
      { name: 'Stability AI', url: 'https://stability.ai', desc: 'Stable Diffusion 开发商' },
      { name: 'Cursor', url: 'https://cursor.sh', desc: 'AI 编程编辑器' },
      { name: 'HuggingFace', url: 'https://huggingface.co', desc: '开源 AI 模型社区' },
      { name: 'Poe', url: 'https://poe.com', desc: '多模型聚合平台' },
      { name: 'Kimi', url: 'https://kimi.moonshot.cn', desc: '月之暗面，超长上下文' },
      { name: '通义千问', url: 'https://tongyi.aliyun.com', desc: '阿里 AI 大模型' },
      { name: 'Copilot', url: 'https://copilot.microsoft.com', desc: '微软 AI 助手' },
      { name: 'Runway', url: 'https://runwayml.com', desc: 'AI 视频生成' },
      { name: 'Suno', url: 'https://suno.com', desc: 'AI 音乐生成' },
      { name: 'Gamma', url: 'https://gamma.app', desc: 'AI 生成 PPT / 文档' },
      { name: 'v0', url: 'https://v0.dev', desc: 'Vercel AI 生成 UI 代码' },
    ],
  },
  {
    title: '软件下载',
    icon: '💻',
    color: 'from-violet-500 to-purple-500',
    items: [
      { name: '果核剥壳', url: 'https://www.ghxi.com', desc: '绿色软件分享，破解资源' },
      { name: '异次元软件', url: 'https://www.iplaysoft.com', desc: '精品软件推荐与教程' },
      { name: '小众软件', url: 'https://www.appinn.com', desc: '发现实用小工具' },
      { name: 'AlternativeTo', url: 'https://alternativeto.net', desc: '找任何软件的替代品' },
      { name: 'FileHorse', url: 'https://www.filehorse.com', desc: '安全无捆绑软件下载' },
      { name: 'PortableApps', url: 'https://portableapps.com', desc: '免安装便携版软件' },
      { name: 'MajorGeeks', url: 'https://www.majorgeeks.com', desc: '老牌软件下载站' },
      { name: 'Softpedia', url: 'https://www.softpedia.com', desc: '海量软件资源库' },
      { name: 'GitHub Releases', url: 'https://github.com/trending', desc: '开源项目热门趋势' },
      { name: 'FileCR', url: 'https://filecr.com', desc: '专业软件资源' },
      { name: 'Winget.run', url: 'https://winget.run', desc: 'Windows 包管理器搜索' },
      { name: 'Snap Store', url: 'https://snapcraft.io', desc: 'Linux 应用商店' },
    ],
  },
  {
    title: '测速工具',
    icon: '⚡',
    color: 'from-amber-500 to-orange-500',
    items: [
      { name: 'Speedtest', url: 'https://www.speedtest.net', desc: '全球最流行的网速测试' },
      { name: 'Fast.com', url: 'https://fast.com', desc: 'Netflix 出品，极简测速' },
      { name: 'Cloudflare Speed', url: 'https://speed.cloudflare.com', desc: 'Cloudflare 官方测速' },
      { name: '测速网', url: 'https://www.speedtest.cn', desc: '国内测速，多节点' },
      { name: 'LibreSpeed', url: 'https://librespeed.org', desc: '开源自部署测速' },
      { name: 'Steam 下载', url: 'https://store.steampowered.com', desc: 'Steam 下载速度实测' },
      { name: 'Bandwidth Place', url: 'https://bandwidthplace.com', desc: 'HTML5 网速测试' },
      { name: 'SpeedOf.me', url: 'https://speedof.me', desc: '浏览器端测速' },
      { name: 'TestMy.net', url: 'https://testmy.net', desc: '自动选择最佳服务器' },
      { name: 'nPerf', url: 'https://nperf.com', desc: '综合网络性能测试' },
      { name: 'OpenSpeedTest', url: 'https://openspeedtest.com', desc: '开源 HTML5 测速' },
      { name: 'Meteor', url: 'https://meteor.speedtestcustom.com', desc: 'Speedtest 出品应用测速' },
    ],
  },
  {
    title: '建站工具',
    icon: '🏗️',
    color: 'from-sky-500 to-blue-500',
    items: [
      { name: 'Cloudflare', url: 'https://www.cloudflare.com', desc: 'CDN / DNS / DDoS 防护' },
      { name: 'Vercel', url: 'https://vercel.com', desc: '前端部署，Next.js 出品' },
      { name: 'Netlify', url: 'https://www.netlify.com', desc: '静态站点托管 + Serverless' },
      { name: 'GitHub Pages', url: 'https://pages.github.com', desc: '免费静态站点托管' },
      { name: "Let's Encrypt", url: 'https://letsencrypt.org', desc: '免费 SSL / TLS 证书' },
      { name: 'WordPress', url: 'https://wordpress.org', desc: '全球最流行的 CMS' },
      { name: 'Nginx Proxy Manager', url: 'https://nginxproxymanager.com', desc: '可视化反向代理管理' },
      { name: 'Namecheap', url: 'https://www.namecheap.com', desc: '便宜域名注册' },
      { name: 'Porkbun', url: 'https://porkbun.com', desc: '便宜域名，免费 WHOIS 隐私' },
      { name: 'Cloudways', url: 'https://www.cloudways.com', desc: '托管型云服务器' },
      { name: 'Hugo', url: 'https://gohugo.io', desc: '极速静态网站生成器' },
      { name: 'Traefik', url: 'https://traefik.io', desc: '云原生反向代理' },
      { name: 'Caddy', url: 'https://caddyserver.com', desc: '自动 HTTPS 的 Web 服务器' },
      { name: 'Coolify', url: 'https://coolify.io', desc: '自部署 Heroku / Vercel 替代' },
    ],
  },
  {
    title: '免费影视',
    icon: '🎬',
    color: 'from-red-500 to-pink-500',
    items: [
      { name: 'LIBVIO', url: 'https://www.libvio.fun', desc: '高清影视在线，资源丰富' },
      { name: '555 电影', url: 'https://www.555dy.com', desc: '免费电影在线看' },
      { name: '樱花动漫', url: 'https://www.yhmgo.com', desc: '免费动漫在线观看' },
      { name: 'AGE 动漫', url: 'https://www.agemys.org', desc: '动漫资源聚合' },
      { name: '嘶哩嘶哩', url: 'https://www.silisili.co', desc: '动漫在线观看' },
      { name: 'FreeOK', url: 'https://www.freeok.vip', desc: '免费影视聚合' },
      { name: '欧乐影院', url: 'https://www.oletv.com', desc: '海外华人影视' },
      { name: '茶杯狐', url: 'https://www.cupfox.app', desc: '影视聚合搜索引擎' },
      { name: '低端影视', url: 'https://ddys.pro', desc: '高清无广告影视' },
      { name: '大师兄影视', url: 'https://dsxys.com', desc: '免费影视资源' },
      { name: 'COKEMV', url: 'https://cokemv.me', desc: '高清影视在线' },
      { name: '人人影视', url: 'https://www.rrys2024.com', desc: '美剧日剧资源' },
    ],
  },
  {
    title: '免费音乐',
    icon: '🎵',
    color: 'from-pink-500 to-rose-500',
    items: [
      { name: 'Spotify', url: 'https://www.spotify.com', desc: '全球最大流媒体音乐' },
      { name: 'SoundCloud', url: 'https://soundcloud.com', desc: '独立音乐人平台' },
      { name: 'Jamendo', url: 'https://www.jamendo.com', desc: '免费 CC 授权音乐' },
      { name: 'Free Music Archive', url: 'https://freemusicarchive.org', desc: '免费合法音乐下载' },
      { name: 'Musopen', url: 'https://musopen.org', desc: '免费古典音乐' },
      { name: 'Pixabay Music', url: 'https://pixabay.com/music', desc: '免费背景音乐' },
      { name: 'Mixkit', url: 'https://mixkit.co/free-stock-music', desc: '免费音乐素材' },
      { name: 'Bensound', url: 'https://www.bensound.com', desc: '免费背景音乐' },
      { name: 'ccMixter', url: 'https://ccmixter.org', desc: 'CC 授权音乐社区' },
      { name: 'Last.fm', url: 'https://www.last.fm', desc: '音乐推荐与发现' },
      { name: 'Bandcamp', url: 'https://bandcamp.com', desc: '独立音乐发行平台' },
      { name: 'Suno AI', url: 'https://suno.com', desc: 'AI 生成音乐' },
    ],
  },
  {
    title: '免费素材',
    icon: '🎨',
    color: 'from-teal-500 to-cyan-500',
    items: [
      { name: 'Unsplash', url: 'https://unsplash.com', desc: '免费高质量摄影图片' },
      { name: 'Pexels', url: 'https://www.pexels.com', desc: '免费图片和视频素材' },
      { name: 'Pixabay', url: 'https://pixabay.com', desc: '免费图片 / 视频 / 音乐' },
      { name: 'Flaticon', url: 'https://www.flaticon.com', desc: '海量免费图标' },
      { name: 'Google Fonts', url: 'https://fonts.google.com', desc: '免费开源字体库' },
      { name: 'ColorHunt', url: 'https://colorhunt.co', desc: '配色方案推荐' },
      { name: 'Remove.bg', url: 'https://www.remove.bg', desc: '一键 AI 抠图' },
      { name: 'Canva', url: 'https://www.canva.com', desc: '在线设计，海量模板' },
      { name: 'Figma', url: 'https://www.figma.com', desc: 'UI / UX 设计工具' },
      { name: 'Mixkit', url: 'https://mixkit.co', desc: '免费视频 / 音乐 / 音效' },
      { name: 'unDraw', url: 'https://undraw.co', desc: '免费 SVG 插画' },
      { name: 'Font Awesome', url: 'https://fontawesome.com', desc: '最流行的图标库' },
      { name: 'Dribbble', url: 'https://dribbble.com', desc: '设计师灵感社区' },
      { name: 'Behance', url: 'https://www.behance.net', desc: 'Adobe 设计作品展示' },
      { name: 'Photoroom', url: 'https://www.photoroom.com', desc: 'AI 背景移除与编辑' },
      { name: 'Freesound', url: 'https://freesound.org', desc: '免费音效素材库' },
    ],
  },
  {
    title: '社区资讯',
    icon: '💬',
    color: 'from-gray-500 to-slate-500',
    items: [
      { name: 'V2EX', url: 'https://www.v2ex.com', desc: '创意工作者社区' },
      { name: 'GitHub', url: 'https://github.com', desc: '全球最大代码托管平台' },
      { name: 'Hacker News', url: 'https://news.ycombinator.com', desc: 'YC 技术新闻社区' },
      { name: 'Product Hunt', url: 'https://www.producthunt.com', desc: '新产品发现平台' },
      { name: '少数派', url: 'https://sspai.com', desc: '效率工具与数字生活' },
      { name: '掘金', url: 'https://juejin.cn', desc: '开发者技术社区' },
      { name: '即刻', url: 'https://okjk.co', desc: '兴趣社交平台' },
      { name: '36Kr', url: 'https://36kr.com', desc: '科技商业资讯' },
      { name: 'Reddit', url: 'https://www.reddit.com', desc: '全球最大兴趣社区' },
      { name: 'Stack Overflow', url: 'https://stackoverflow.com', desc: '编程问答社区' },
      { name: 'Dev.to', url: 'https://dev.to', desc: '开发者博客社区' },
      { name: 'InfoQ', url: 'https://www.infoq.cn', desc: '技术深度文章' },
      { name: 'Explain Shell', url: 'https://explainshell.com', desc: 'Shell 命令可视化解释' },
      { name: 'LeetCode', url: 'https://leetcode.cn', desc: '算法刷题平台' },
      { name: 'Crunchbase', url: 'https://www.crunchbase.com', desc: '创业公司数据库' },
      { name: 'TechCrunch', url: 'https://techcrunch.com', desc: '科技创业新闻' },
    ],
  },
  {
    title: '前端开发',
    icon: '🎨',
    color: 'from-sky-400 to-blue-500',
    items: [
      { name: 'MDN', url: 'https://developer.mozilla.org', desc: 'Web 技术权威文档' },
      { name: 'Can I Use', url: 'https://caniuse.com', desc: '浏览器兼容性速查' },
      { name: 'React', url: 'https://react.dev', desc: 'Meta 出品 UI 库' },
      { name: 'Vue.js', url: 'https://vuejs.org', desc: '渐进式 JavaScript 框架' },
      { name: 'Next.js', url: 'https://nextjs.org', desc: 'React 全栈框架' },
      { name: 'Nuxt', url: 'https://nuxt.com', desc: 'Vue 全栈框架' },
      { name: 'Tailwind CSS', url: 'https://tailwindcss.com', desc: '原子化 CSS 框架' },
      { name: 'Vite', url: 'https://vitejs.dev', desc: '极速前端构建工具' },
      { name: 'TypeScript', url: 'https://www.typescriptlang.org', desc: 'JavaScript 超集，类型安全' },
      { name: 'Svelte', url: 'https://svelte.dev', desc: '编译时前端框架' },
      { name: 'Element Plus', url: 'https://element-plus.org', desc: 'Vue 3 UI 组件库' },
      { name: 'Ant Design', url: 'https://ant.design', desc: 'React 企业级 UI 组件库' },
      { name: 'Webpack', url: 'https://webpack.js.org', desc: '模块打包器' },
      { name: 'Astro', url: 'https://astro.build', desc: '内容优先的 Web 框架' },
    ],
  },
  {
    title: '后端开发',
    icon: '⚙️',
    color: 'from-emerald-500 to-green-600',
    items: [
      { name: 'Node.js', url: 'https://nodejs.org', desc: 'JavaScript 运行时' },
      { name: 'Python', url: 'https://www.python.org', desc: '通用编程语言' },
      { name: 'Go', url: 'https://go.dev', desc: 'Google 出品，高并发' },
      { name: 'Rust', url: 'https://www.rust-lang.org', desc: '内存安全系统语言' },
      { name: 'Java', url: 'https://dev.java', desc: '企业级编程语言' },
      { name: 'Spring Boot', url: 'https://spring.io/projects/spring-boot', desc: 'Java 微服务框架' },
      { name: 'Django', url: 'https://www.djangoproject.com', desc: 'Python 全栈框架' },
      { name: 'FastAPI', url: 'https://fastapi.tiangolo.com', desc: 'Python 高性能 API 框架' },
      { name: 'Gin', url: 'https://gin-gonic.com', desc: 'Go HTTP Web 框架' },
      { name: 'Express.js', url: 'https://expressjs.com', desc: 'Node.js Web 框架' },
      { name: 'Laravel', url: 'https://laravel.com', desc: 'PHP Web 框架' },
      { name: 'PostgreSQL', url: 'https://www.postgresql.org', desc: '最强开源关系型数据库' },
      { name: 'MySQL', url: 'https://www.mysql.com', desc: '最流行的开源数据库' },
      { name: 'Redis', url: 'https://redis.io', desc: '内存数据库 / 缓存' },
      { name: 'MongoDB', url: 'https://www.mongodb.com', desc: '文档型 NoSQL 数据库' },
      { name: 'GORM', url: 'https://gorm.io', desc: 'Go ORM 库' },
    ],
  },
  {
    title: '云原生',
    icon: '☁️',
    color: 'from-cyan-500 to-blue-500',
    items: [
      { name: 'Kubernetes', url: 'https://kubernetes.io', desc: '容器编排标准' },
      { name: 'Docker', url: 'https://www.docker.com', desc: '容器化平台' },
      { name: 'Helm', url: 'https://helm.sh', desc: 'K8s 包管理器' },
      { name: 'Istio', url: 'https://istio.io', desc: '服务网格' },
      { name: 'Prometheus', url: 'https://prometheus.io', desc: '云原生监控标准' },
      { name: 'Grafana', url: 'https://grafana.com', desc: '可观测性平台' },
      { name: 'Envoy', url: 'https://www.envoyproxy.io', desc: '高性能代理' },
      { name: 'containerd', url: 'https://containerd.io', desc: '容器运行时' },
      { name: 'Fluentd', url: 'https://www.fluentd.org', desc: '统一日志层' },
      { name: 'Jaeger', url: 'https://www.jaegertracing.io', desc: '分布式链路追踪' },
      { name: 'OpenTelemetry', url: 'https://opentelemetry.io', desc: '可观测性标准框架' },
      { name: 'CoreDNS', url: 'https://coredns.io', desc: 'K8s DNS 服务' },
    ],
  },
  {
    title: '运维',
    icon: '🛠️',
    color: 'from-orange-500 to-amber-500',
    items: [
      { name: 'Ansible', url: 'https://www.ansible.com', desc: '自动化运维工具' },
      { name: 'Terraform', url: 'https://www.terraform.io', desc: '基础设施即代码' },
      { name: 'Packer', url: 'https://www.packer.io', desc: '自动化镜像构建' },
      { name: 'Zabbix', url: 'https://www.zabbix.com', desc: '企业级监控平台' },
      { name: 'ELK Stack', url: 'https://www.elastic.co', desc: 'Elasticsearch + Logstash + Kibana' },
      { name: 'Datadog', url: 'https://www.datadoghq.com', desc: '云监控与分析' },
      { name: 'PagerDuty', url: 'https://www.pagerduty.com', desc: '事件响应平台' },
      { name: 'RunDeck', url: 'https://www.rundeck.com', desc: '运维自动化平台' },
      { name: 'Nagios', url: 'https://www.nagios.org', desc: '经典 IT 监控系统' },
      { name: 'Nginx', url: 'https://nginx.org', desc: '高性能 Web 服务器' },
      { name: 'Caddy', url: 'https://caddyserver.com', desc: '自动 HTTPS Web 服务器' },
      { name: 'Netdata', url: 'https://www.netdata.cloud', desc: '实时性能监控' },
    ],
  },
  {
    title: 'CI/CD',
    icon: '🔄',
    color: 'from-lime-500 to-green-500',
    items: [
      { name: 'Jenkins', url: 'https://www.jenkins.io', desc: '最流行的 CI/CD 服务器' },
      { name: 'GitHub Actions', url: 'https://github.com/features/actions', desc: 'GitHub 原生 CI/CD' },
      { name: 'GitLab CI', url: 'https://docs.gitlab.com/ee/ci', desc: 'GitLab 内置 CI/CD' },
      { name: 'CircleCI', url: 'https://circleci.com', desc: '云端 CI/CD 平台' },
      { name: 'Argo CD', url: 'https://argoproj.github.io/cd', desc: 'GitOps 持续交付' },
      { name: 'Flux', url: 'https://fluxcd.io', desc: 'GitOps K8s 工具集' },
      { name: 'Tekton', url: 'https://tekton.dev', desc: '云原生 CI/CD 框架' },
      { name: 'Drone', url: 'https://www.drone.io', desc: '容器原生 CI 平台' },
      { name: 'Travis CI', url: 'https://www.travis-ci.com', desc: '开源项目 CI 服务' },
      { name: 'Concourse', url: 'https://concourse-ci.org', desc: '可伸缩 CI 系统' },
      { name: 'Woodpecker CI', url: 'https://woodpecker-ci.org', desc: 'Drone 分支，社区驱动' },
      { name: 'Dagger', url: 'https://dagger.io', desc: '可编程 CI/CD 引擎' },
    ],
  },
  {
    title: '大数据',
    icon: '📊',
    color: 'from-purple-500 to-indigo-500',
    items: [
      { name: 'Apache Hadoop', url: 'https://hadoop.apache.org', desc: '分布式计算框架' },
      { name: 'Apache Spark', url: 'https://spark.apache.org', desc: '统一计算引擎' },
      { name: 'Apache Kafka', url: 'https://kafka.apache.org', desc: '分布式事件流平台' },
      { name: 'Apache Flink', url: 'https://flink.apache.org', desc: '流批一体计算引擎' },
      { name: 'Elasticsearch', url: 'https://www.elastic.co/elasticsearch', desc: '分布式搜索与分析引擎' },
      { name: 'ClickHouse', url: 'https://clickhouse.com', desc: '极速列式数据库' },
      { name: 'Apache Airflow', url: 'https://airflow.apache.org', desc: '工作流编排平台' },
      { name: 'Apache Doris', url: 'https://doris.apache.org', desc: '实时分析数据库' },
      { name: 'Apache Hive', url: 'https://hive.apache.org', desc: 'Hadoop SQL 查询引擎' },
      { name: 'Presto', url: 'https://prestodb.io', desc: '分布式 SQL 查询引擎' },
      { name: 'Apache NiFi', url: 'https://nifi.apache.org', desc: '数据流自动化' },
      { name: 'dbt', url: 'https://www.getdbt.com', desc: '数据转换工具' },
    ],
  },
  {
    title: 'NSFW',
    icon: '🔥',
    color: 'from-rose-500 to-red-600',
    items: [
      { name: 'XVideos', url: 'https://www.xvideos.com', desc: '全球最大成人视频站' },
      { name: 'Pornhub', url: 'https://www.pornhub.com', desc: '知名成人视频平台' },
      { name: 'XHamster', url: 'https://xhamster.com', desc: '免费成人视频' },
      { name: 'SpankBang', url: 'https://spankbang.com', desc: '高清成人视频' },
      { name: 'E-Hentai', url: 'https://e-hentai.org', desc: '同人志 / 漫画资源' },
      { name: 'nhentai', url: 'https://nhentai.net', desc: '在线漫画阅读' },
      { name: '91porn', url: 'https://91porn.com', desc: '华人原创视频' },
      { name: 'XNXX', url: 'https://www.xnxx.com', desc: '免费成人视频' },
      { name: 'YouPorn', url: 'https://www.youporn.com', desc: '成人视频平台' },
      { name: 'Rule34', url: 'https://rule34.xxx', desc: '同人创作社区' },
      { name: 'Hanime', url: 'https://hanime.tv', desc: '成人动漫视频' },
      { name: 'Brazzers', url: 'https://www.brazzers.com', desc: '知名制作商' },
    ],
  },
  {
    title: '番号搜索',
    icon: '🔎',
    color: 'from-fuchsia-500 to-pink-500',
    items: [
      { name: 'JavDB', url: 'https://javdb.com', desc: '最全番号数据库 + 评分' },
      { name: 'JavLibrary', url: 'https://www.javlibrary.com', desc: '番号资料库 + 评论' },
      { name: 'JavMost', url: 'https://javmost.com', desc: '番号聚合搜索' },
      { name: 'JavModel', url: 'https://javmodel.com', desc: '女优资料查询' },
      { name: 'MissAV', url: 'https://missav.ws', desc: '在线观看 + 番号搜索' },
      { name: 'SupJav', url: 'https://supjav.com', desc: '番号在线搜索' },
      { name: 'Jav.guru', url: 'https://jav.guru', desc: '番号搜索 + 在线' },
      { name: 'JAV HD', url: 'https://javhd.com', desc: '高清 JAV 资源' },
      { name: 'JavFinder', url: 'https://javfinder.is', desc: '番号磁力搜索' },
      { name: 'JavFree', url: 'https://javfree.me', desc: '番号资源分享' },
      { name: 'AVJiali', url: 'https://avjiali.com', desc: '亚洲 AV 资源' },
      { name: 'JAV.Downloader', url: 'https://javdownloader.com', desc: '番号下载工具' },
    ],
  },
  {
    title: '网络诊断',
    icon: '🌐',
    color: 'from-green-500 to-emerald-500',
    items: [
      { name: 'Ping.pe', url: 'https://ping.pe', desc: '全球 Ping / MTR / 路由追踪' },
      { name: 'IP.SB', url: 'https://ip.sb', desc: 'IP 信息查询，支持 IPv6' },
      { name: '站长工具', url: 'https://tool.chinaz.com', desc: 'DNS / Whois / Ping 综合工具' },
      { name: 'DNSChecker', url: 'https://dnschecker.org', desc: '全球 DNS 传播检查' },
      { name: 'SSL Labs', url: 'https://www.ssllabs.com/ssltest', desc: 'SSL / TLS 安全评级' },
      { name: 'Boce', url: 'https://www.boce.com', desc: '拨测，国内网络诊断' },
      { name: 'IT Dog', url: 'https://www.itdog.cn', desc: 'TCPing / DNS / 路由追踪' },
      { name: 'Sucuri', url: 'https://sitecheck.sucuri.net', desc: '网站安全与恶意软件检测' },
      { name: 'DNS Lookup', url: 'https://dnslookup.online', desc: '在线 DNS 查询工具' },
      { name: 'WhatIsMyIP', url: 'https://whatismyipaddress.com', desc: 'IP 地址与网络信息' },
      { name: 'ViewDNS', url: 'https://viewdns.info', desc: 'DNS 历史记录与反向查询' },
      { name: 'SecurityHeaders', url: 'https://securityheaders.com', desc: 'HTTP 安全响应头检测' },
    ],
  },
]
